export enum GameState {
  USER_REGISTERING = "UserRegistering",
  ROOM_CREATION = "RoomCreation",
  GAME_START = "GAME_START",
  ROUND_ANNOUNCEMENT = "ROUND_ANNOUNCEMENT",
  WORD_SELECTION = "WORD_SELECTION",
  TURN_STARTING = "TURN_STARTING",
  TURN_END = "TURN_END",
  TURN_SCORE = "TURN_SCORE",
  GAME_END = "GAME_END",
}
